# Generated by Django 5.0.1 on 2024-02-01 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(default=None, max_length=1000)),
                ('summary', models.CharField(default='', max_length=500)),
                ('publication_date', models.DateTimeField(verbose_name='publication date')),
                ('last_modification_date', models.DateTimeField(verbose_name='last modification date')),
                ('tags', models.JSONField()),
                ('ratings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(default=1, max_length=200)),
                ('image', models.CharField(default='', max_length=1000)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1500)),
                ('image', models.JSONField()),
                ('order', models.IntegerField(default=0)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.blogposts')),
            ],
        ),
        migrations.AddField(
            model_name='blogposts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.customuser'),
        ),
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.blogposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=500)),
                ('cooking_time', models.IntegerField(default=0)),
                ('difficulty_level', models.CharField(max_length=10)),
                ('ingredients', models.JSONField()),
                ('tags', models.JSONField()),
                ('rating', models.IntegerField(default=0)),
                ('meal_type', models.CharField(max_length=200)),
                ('last_edited', models.DateTimeField(auto_now=True, verbose_name='last edited')),
                ('image', models.CharField(default=None, max_length=1000)),
                ('video', models.CharField(default=None, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipes', models.ManyToManyField(to='MyApp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('step', models.CharField(max_length=200)),
                ('image', models.CharField(default=None, max_length=1000)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='reviews',
            field=models.ManyToManyField(to='MyApp.review'),
        ),
    ]
