# Generated by Django 5.0.1 on 2024-02-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_customuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSearchTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeSearchTags',
            field=models.ManyToManyField(to='MyApp.recipesearchtags'),
        ),
    ]
