# Generated by Django 5.0.1 on 2024-02-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_recipesearchtags_recipe_recipesearchtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='summary',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipesteps',
            name='step',
            field=models.CharField(max_length=1000),
        ),
    ]
