# Generated by Django 5.0.1 on 2024-02-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_blogposts_summary_alter_recipesteps_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsWithNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('calorie', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('carbohydrate', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=models.JSONField(default=dict),
        ),
    ]
