# Generated by Django 5.0.1 on 2024-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_ingredientswithnutrition_recipe_nutrition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
