# Generated by Django 5.0.1 on 2024-02-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_remove_recipe_nutrition_recipe_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientswithnutrition',
            name='gm_weight',
            field=models.IntegerField(default=0),
        ),
    ]
