# Generated by Django 5.0.1 on 2024-02-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_blogposts_rater_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
    ]
