# Generated by Django 5.0.1 on 2024-02-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_alter_blogposts_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='ratings',
            field=models.IntegerField(default=0.0),
        ),
    ]
