# Generated by Django 5.0.1 on 2024-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_alter_blogposts_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
