# Generated by Django 5.0.1 on 2024-02-29 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_remove_blogposts_rater_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ratings',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='RecipeComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('recipe_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='RecipePostRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('recipe_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.customuser')),
            ],
        ),
    ]
