# Generated by Django 5.0.1 on 2024-02-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_remove_recipe_rating_recipe_ratings_recipecomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MyApp.blogposts'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='is_recipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MyApp.recipe'),
        ),
    ]
