# Generated by Django 5.0.1 on 2024-02-29 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_notifications_blog_notifications_is_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.blogposts'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.recipe'),
        ),
    ]
