# Generated by Django 5.0.1 on 2024-03-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_alter_notifications_blog_alter_notifications_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSearchTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blogposts',
            name='blogSearchTags',
            field=models.ManyToManyField(to='MyApp.blogsearchtags'),
        ),
    ]
